name: Terraform destroy
on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy resources'
        required: true
env:
  AWS_REGION: ap-south-1
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
   
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init
      
    - name: Destroy resources
      run: terraform destroy -var-file=chitra.tfvars  -auto-approve 
